apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: oms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: oms/gateway:latest
        ports:
        - containerPort: 5000
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:8001"
        - name: ORDER_SERVICE_URL
          value: "http://order-service:8002"
        - name: INVENTORY_SERVICE_URL
          value: "http://inventory-service:8003"
        - name: SWAGGER_SERVICE_URL
          value: "http://swagger-service:8004"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: oms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: oms/ms-auth:latest
        ports:
        - containerPort: 8001
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: jdbc-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: oms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: oms/ms-order:latest
        ports:
        - containerPort: 8002
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: jdbc-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: INVENTORY_SERVICE_URL
          value: "http://inventory-service:8003"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: oms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: oms/ms-inventory:latest
        ports:
        - containerPort: 8003
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: jdbc-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        envFrom:
        - configMapRef:
            name: inventory-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-service
  namespace: oms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger-service
  template:
    metadata:
      labels:
        app: swagger-service
    spec:
      containers:
      - name: swagger-service
        image: oms/ms-swagger:latest
        ports:
        - containerPort: 8004
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:8001"
        - name: ORDER_SERVICE_URL
          value: "http://order-service:8002"
        - name: INVENTORY_SERVICE_URL
          value: "http://inventory-service:8003"