apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: oms
spec:
  selector:
    app: gateway
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: oms
spec:
  selector:
    app: auth-service
  ports:
  - port: 8001
    targetPort: 8001
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: oms
spec:
  selector:
    app: order-service
  ports:
  - port: 8002
    targetPort: 8002
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: oms
spec:
  selector:
    app: inventory-service
  ports:
  - port: 8003
    targetPort: 8003
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: swagger-service
  namespace: oms
spec:
  selector:
    app: swagger-service
  ports:
  - port: 8004
    targetPort: 8004
  type: ClusterIP